language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '14'

before_script:
  - yarn build

after_success:
  - yarn semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
